@HostAddress = https://localhost:5001

### Get a list of habits

< {%
    request.variables.set("q", "")
    request.variables.set("type", "")
    request.variables.set("status", "")
%}
GET {{HostAddress}}/habits
    ?q={{q}}
    &type={{type}}
    &status={{status}}
Accept: application/json

### Get habit by ID

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
GET {{HostAddress}}/habits/{{id}}
Accept: application/json

### Create habit

POST {{HostAddress}}/habits
Accept: application/json
Content-Type: application/json

{
  "name": "type 1",
  "description": null,
  "type": 1,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 30,
    "unit": "sessions"
  }
}

### Update habit

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
PUT {{HostAddress}}/habits/{{id}}
Accept: application/json
Content-Type: application/json

{
  "name": "Daily coding",
  "description": "The new description of the habit",
  "type": 2,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 45,
    "unit": "minutes"
  },
  "milestone": {
    "target": 100
  }
}

### Partially update habit

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
PATCH {{HostAddress}}/habits/{{id}}
Accept: application/json
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/name",
    "value": "Daily coding updated"
  },
  {
    "op": "replace",
    "path": "/description",
    "value": "description updated"
  }
]

### Delete habit

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
DELETE {{HostAddress}}/habits/{{id}}
Accept: application/json