@HostAddress = https://localhost:5001

### Get a list of tags

GET {{HostAddress}}/tags
Accept: application/json

### Get tag by ID

< {%
    request.variables.set("id", "t_019b8656-0745-77f2-a5b2-c3cbbdb38125")
%}
GET {{HostAddress}}/tags/{{id}}
Accept: application/json

### Create tag

POST {{HostAddress}}/tags
Accept: application/json
Content-Type: application/json

{
  "name": "asdads",
  "description": "new desc 2"
}

### Update tag

< {%
    request.variables.set("id", "t_019b8656-0745-77f2-a5b2-c3cbbdb38125")
%}
PUT {{HostAddress}}/tags/{{id}}
Accept: application/json
Content-Type: application/json

{
  "name": "updated tag",
  "description": "updated desc"
}

### Delete tag

< {%
    request.variables.set("id", "t_019b8656-0745-77f2-a5b2-c3cbbdb38125")
%}
DELETE {{HostAddress}}/tags/{{id}}
Accept: application/json