### Register user

POST {{hostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "filip@devhabit.com",
  "name": "Filip M",
  "password": "filipM123!",
  "confirmPassword": "filipM123!"
}

### Login user

POST {{hostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "filip@devhabit.com",
  "password": "filipM123!"
}

### Refresh token

POST {{hostAddress}}/auth/refresh
Accept: application/json
Content-Type: application/json

{
  "value": "75M9acXMh2dJrwTQbbyoDJITcufyFJH5jZbZvCOQlhQ="
}

###