@HostAddress = https://localhost:5001

### Register user

POST {{HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "filip@devhabit.com",
  "name": "Filip M",
  "password": "filipM123!",
  "confirmPassword": "filipM123!"
}

###