### Upsert habit tags

< {%
    request.variables.set("habitId", "h_019b95a1-dca5-77ab-8397-af00c432ebd6")
%}
PUT {{hostAddress}}/habits/{{habitId}}/tags
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tagIds": [
    "t_019b95a2-9154-75e6-b651-81855c4f8116"
  ]
}

### Remove habit tag

< {%
    request.variables.set("habitId", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
    request.variables.set("tagId", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
DELETE {{hostAddress}}/habits/{{habitId}}/tags/{{tagId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

###