### Get paginated habits

< {%
    request.variables.set("q", "")
    request.variables.set("type", "")
    request.variables.set("status", "")
    request.variables.set("sort", "")
    request.variables.set("fields", "name")
    request.variables.set("page", "1")
    request.variables.set("pageSize", "10")
%}
GET {{hostAddress}}/habits
    ?q={{q}}
    &type={{type}}
    &status={{status}}
    &sort={{sort}}
    &fields={{fields}}
    &page={{page}}
    &pageSize={{pageSize}}
Accept: application/vnd.dev-habit.hateoas+json
Authorization: Bearer {{accessToken}}
# Accept: application/json

### Get habit by ID

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
    request.variables.set("fields", "")
%}
GET {{hostAddress}}/habits/{{id}}?fields={{fields}}
Accept: application/vnd.dev-habit.hateoas+json
Authorization: Bearer {{accessToken}}
# Accept: application/json

### Create habit

POST {{hostAddress}}/habits
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "type 2",
  "description": null,
  "type": 2,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 30,
    "unit": "sessions"
  }
}

### Update habit

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
PUT {{hostAddress}}/habits/{{id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Daily coding",
  "description": "The new description of the habit",
  "type": 2,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 45,
    "unit": "minutes"
  },
  "milestone": {
    "target": 100
  }
}

### Partially update habit

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
PATCH {{hostAddress}}/habits/{{id}}
Accept: application/json
Content-Type: application/json-patch+json
Authorization: Bearer {{accessToken}}

[
  {
    "op": "replace",
    "path": "/name",
    "value": "Daily coding updated"
  },
  {
    "op": "replace",
    "path": "/description",
    "value": "description updated"
  }
]

### Delete habit

< {%
    request.variables.set("id", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
DELETE {{hostAddress}}/habits/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}