### Upsert habit tags

< {%
    request.variables.set("habitId", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
PUT {{hostAddress}}/habits/{{habitId}}/tags
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tagIds": [
    "t_019b8658-2e4b-73cd-8702-9ef2d6428cfa",
    "t_019b8670-9c8d-7e43-8a42-73fa3481867b"
  ]
}

### Remove habit tag

< {%
    request.variables.set("habitId", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
    request.variables.set("tagId", "h_019b8605-21ab-7b4a-aa47-74d92a436087")
%}
DELETE {{hostAddress}}/habits/{{habitId}}/tags/{{tagId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

###