### Get a list of tags

GET {{hostAddress}}/tags
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get tag by ID

< {%
    request.variables.set("id", "t_019b8656-0745-77f2-a5b2-c3cbbdb38125")
%}
GET {{hostAddress}}/tags/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create tag

POST {{hostAddress}}/tags
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "asdads",
  "description": "new desc 2"
}

### Update tag

< {%
    request.variables.set("id", "t_019b8656-0745-77f2-a5b2-c3cbbdb38125")
%}
PUT {{hostAddress}}/tags/{{id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "updated tag",
  "description": "updated desc"
}

### Delete tag

< {%
    request.variables.set("id", "t_019b8656-0745-77f2-a5b2-c3cbbdb38125")
%}
DELETE {{hostAddress}}/tags/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}