### Get user

< {%
    request.variables.set("id", "u_019b9588-9816-7ca9-ac93-0cb1e1dc10d2")
%}
GET {{hostAddress}}/users/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get current user

GET {{hostAddress}}/users/me
Accept: application/json
Authorization: Bearer {{accessToken}}

###