### Get user

< {%
    request.variables.set("id", "u_019b8efc-dad3-7eff-a395-ca39d9d330f1")
%}
GET {{hostAddress}}/users/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get current user

GET {{hostAddress}}/users/me
Accept: application/json
Authorization: Bearer {{accessToken}}

### Update current user

PUT {{hostAddress}}/users/me
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "New name"
}